# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: extension-test
on: [ push, workflow_dispatch ]

jobs:

###############################################################################
# Extension Build verification
####
  extension-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: report-react
    - run: npm install
      working-directory: accessibility-checker-extension
    - run: npm install
      working-directory: rule-server
    - run: npm run build
      working-directory: rule-server
    - run: sed -i'.old' -e "s/[\"|']use strict[\"|']//g" ./exceljs.js
      working-directory: accessibility-checker-extension/node_modules/exceljs/dist
    - run: sed -i'.old' -e "s/[\"|']use strict[\"|']//g" ./exceljs.min.js
      working-directory: accessibility-checker-extension/node_modules/exceljs/dist
    - run: cp -f ./manifest_Chrome.json ./src/manifest.json
      working-directory: accessibility-checker-extension
    - run: npm run package:browser
      working-directory: accessibility-checker-extension
    - name: Upload packed extension
      uses: actions/upload-artifact@v1
      with:
        name: accessibility-checker-extension for Chrome
        path: accessibility-checker-extension/package/accessibility-checker-extension.zip
    - run: cp -f ./manifest_Firefox.json ./src/manifest.json
      working-directory: accessibility-checker-extension
    - run: npm run package:browser
      working-directory: accessibility-checker-extension
    - name: Upload packed extension
      uses: actions/upload-artifact@v1
      with:
        name: accessibility-checker-extension for Firefox
        path: accessibility-checker-extension/package/accessibility-checker-extension.zip

  rule-deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: rule-server
    - run: npm run build
      working-directory: rule-server
    - run: gitactions/publish/rules.sh
      env: 
        BLUEMIX_USERID: apikey
        BLUEMIX_PASS: ${{ secrets.BLUEMIX_PASS }}
        CLOUD_PWD: ${{ secrets.CLOUD_PWD }}
        TRAVIS_BRANCH: sandbox
